name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ./.github/scripts/initBuildEnv.sh
        env:
          GCP_SA_KEY_DEV: ${{secrets.GCP_SA_KEY_DEV}}
          GCP_SA_KEY_PROD: ${{secrets.GCP_SA_KEY_PROD}}
          GCP_SA_KEY_STAGING: ${{secrets.GCP_SA_KEY_STAGING}}
      - uses: actions/setup-node@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - run: yarn build
      - run: yarn npm publish
        if: startsWith(github.ref, 'refs/tags')
